//This is the sequence_item block which contains the input and output variables
// this is a single object that carries data through the whole flow , alos stores intermediate ref model results
class seqitem_g17 extends uvm_sequence_item;

	`uvm_object_utils(seqitem_g17)
	 bit Clk;
	 bit Reset;
	 bit Pushin;
	 bit FirstData;
	 reg signed [16:0] DinR;
	 reg signed [16:0] DinI;
	 rand bit [47:0] DataIn;
	 
	 // Outputs
	 bit PushOut;
	reg [47:0] DataOut;  // actual output caputured by the monitor
	logic  [47:0] DataOut1; //expected output generated by the ref model FFT+ decoder path
	real temp[128]; // used by the ref model to store the reconstructed values
	reg signed [16:0]  realfp[128]; // fixed point converted into time domian samples
	reg signed [16:0]  imgfp[128]; // fixed point converted into time domian samples
	 
	typedef struct  {
		real re; 
		real im;
		} complex_num;
											    
	complex_num complexout[128],timeout[128];// freq domain subcarrier values after encoding , holds the time domain IFFT output samples
		   
	function new (string name = "seqitem_g17");    
		super.new(name);
	endfunction: new

endclass : seqitem_g17



